//
// Created by cheny on 24-9-18.
//

#ifndef DART_MCU_DART_CONFIG_H
#define DART_MCU_DART_CONFIG_H

#include "stdint.h"
#include "dart_launcher_param.h"

// 比赛模式相关
#define CONFIG_FORCE_WAIT_FOR_GAME_PROGRESS 1
// 开舱门自瞄时间
#define CONFIG_AUTOAIM_TIMEOUT_MS 1000

// 时间相关
#define CONFIG_SLIDE_SERVO_SLIDE_TIME 200
#define CONFIG_LIFT_WAIT_TIME 1000
#define CONFIG_LAUNCH_WAIT_TIME 500

// 丝杆电机复位堵转速度
#define CONFIG_TARGET_RESET_VELOCITY_YAWLS -100
#define CONFIG_TARGET_RESET_VELOCITY_PITCHLS -100
#define CONFIG_TARGET_RESET_VELOCITY_TRIGGERLS -5000
#define CONFIG_GATE_VELOCITY_TRIGGERLS 1000
#define CONFIG_GATE_CURRENT_TRIGGERLS 2000
#define CONFIG_TIMEOUT_RESET_TRIGGER 100

// 该角度直接触发击发，0代表左边的，1代表右边的舵机（后视）
#define CONFIG_TRIGGER_SERVO_TRIGGER_ANGLE_0 80
#define CONFIG_TRIGGER_SERVO_TRIGGER_ANGLE_1 40
// 该角度为重新装填的默认角度
#define CONFIG_TRIGGER_SERVO_RELOAD_ANGLE_0 65
#define CONFIG_TRIGGER_SERVO_RELOAD_ANGLE_1 0
// 该角度为升降机在上时左右侧舵机的角度
#define CONFIG_LOAD_SERVO_UP_ANGLE_0 200
#define CONFIG_LOAD_SERVO_UP_ANGLE_1 70

// 该角度为升降机在下时左右侧舵机的角度
#define CONFIG_LOAD_SERVO_DOWN_ANGLE_0 67
#define CONFIG_LOAD_SERVO_DOWN_ANGLE_1 203

#define CONFIG_SLIDE_SERVO_SLIDE_ANGLE 50
#define CONFIG_SLIDE_SERVO_CUT_ANGLE 80

// 复位堵转速度和超时时间
#define CONFIG_TARGET_RESET_VELOCITY_LOAD 1000
#define CONFIG_GATE_VELOCITY_LOAD 100
#define CONFIG_TIMEOUT_RESET_LOAD 1000

// 电机角度限制
#define CONFIG_MOTOR_PITCH_ANGLE_MAX 8192
#define CONFIG_MOTOR_YAW_ANGLE_MAX 8192
#define CONFIG_MOTOR_TRIGGER_ANGLE_MAX 8192
#define CONFIG_MOTOR_LOAD_ANGLE_MAX 8192

// 特殊电机角度定义
#define CONFIG_MOTOR_LOAD_ANGLE_UP 10000
#define CONFIG_MOTOR_LOAD_ANGLE_POST_LOAD 250000
#define CONFIG_MOTOR_LOAD_ANGLE_DOWN 950000

// 运动速度定义
#define CONFIG_MOTOR_LOAD_OPERATION_VELOCITY_DOWNWARD 5000

extern DartLauncherParams dart_launcher_params;
extern DartLauncherStatus dart_launcher_status;

#endif //DART_MCU_DART_CONFIG_H
