//
// Created by cheny on 24-9-18.
//

#ifndef DART_MCU_DART_CONFIG_H
#define DART_MCU_DART_CONFIG_H

#define CONFIG_TARGET_RESET_VELOCITY_YAWLS 1000
#define CONFIG_TARGET_RESET_VELOCITY_PITCHLS 1000
#define CONFIG_TARGET_RESET_VELOCITY_TRIGGERLS 1000

// 该角度直接触发击发
#define CONFIG_TRIGGER_SERVO_TRIGGER_ANGLE 90
// 该角度为重新装填的默认角度
#define CONFIG_TRIGGER_SERVO_RELOAD_ANGLE 0

#define CONFIG_TARGET_RESET_VELOCITY_LOAD 1000
#define CONFIG_GATE_VELOCITY_LOAD 100
#define CONFIG_TIMEOUT_RESET_LOAD 1000

#endif //DART_MCU_DART_CONFIG_H
